"""empty message

Revision ID: 31c1cbe832fd
Revises: 
Create Date: 2021-06-02 19:56:18.765224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c1cbe832fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_hospital_tsj',
    sa.Column('leave_tsj_id', sa.VARCHAR(length=20), nullable=False, comment='同视机(出院)表id'),
    sa.Column('base_info_id', sa.VARCHAR(length=20), nullable=True, comment='基本表id'),
    sa.Column('leave_tsj_tss', sa.Boolean(), nullable=True, comment='同时视(出院)'),
    sa.Column('leave_tsj_tss_sp', sa.VARCHAR(length=20), nullable=True, comment='同时视水平值(出院)'),
    sa.Column('leave_tsj_tss_cz', sa.VARCHAR(length=20), nullable=True, comment='同时视垂直值（R/L or L/R）(出院)'),
    sa.Column('leave_tsj_tss_cs_z', sa.VARCHAR(length=20), nullable=True, comment='同时视垂直值具体数值(出院)'),
    sa.ForeignKeyConstraint(['base_info_id'], ['base_info.id'], ),
    sa.PrimaryKeyConstraint('leave_tsj_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_hospital_tsj')
    # ### end Alembic commands ###
